/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PublishedRouteImport } from './routes/published'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListingsIdRouteImport } from './routes/listings/$id'
import { Route as AuthEbayCallbackRouteImport } from './routes/auth/ebay/callback'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishedRoute = PublishedRouteImport.update({
  id: '/published',
  path: '/published',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIdRoute = ListingsIdRouteImport.update({
  id: '/listings/$id',
  path: '/listings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthEbayCallbackRoute = AuthEbayCallbackRouteImport.update({
  id: '/auth/ebay/callback',
  path: '/auth/ebay/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/debug': typeof DebugRoute
  '/published': typeof PublishedRoute
  '/settings': typeof SettingsRoute
  '/listings/$id': typeof ListingsIdRoute
  '/auth/ebay/callback': typeof AuthEbayCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/debug': typeof DebugRoute
  '/published': typeof PublishedRoute
  '/settings': typeof SettingsRoute
  '/listings/$id': typeof ListingsIdRoute
  '/auth/ebay/callback': typeof AuthEbayCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/debug': typeof DebugRoute
  '/published': typeof PublishedRoute
  '/settings': typeof SettingsRoute
  '/listings/$id': typeof ListingsIdRoute
  '/auth/ebay/callback': typeof AuthEbayCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/debug'
    | '/published'
    | '/settings'
    | '/listings/$id'
    | '/auth/ebay/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/debug'
    | '/published'
    | '/settings'
    | '/listings/$id'
    | '/auth/ebay/callback'
  id:
    | '__root__'
    | '/'
    | '/debug'
    | '/published'
    | '/settings'
    | '/listings/$id'
    | '/auth/ebay/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DebugRoute: typeof DebugRoute
  PublishedRoute: typeof PublishedRoute
  SettingsRoute: typeof SettingsRoute
  ListingsIdRoute: typeof ListingsIdRoute
  AuthEbayCallbackRoute: typeof AuthEbayCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/published': {
      id: '/published'
      path: '/published'
      fullPath: '/published'
      preLoaderRoute: typeof PublishedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$id': {
      id: '/listings/$id'
      path: '/listings/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof ListingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/ebay/callback': {
      id: '/auth/ebay/callback'
      path: '/auth/ebay/callback'
      fullPath: '/auth/ebay/callback'
      preLoaderRoute: typeof AuthEbayCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DebugRoute: DebugRoute,
  PublishedRoute: PublishedRoute,
  SettingsRoute: SettingsRoute,
  ListingsIdRoute: ListingsIdRoute,
  AuthEbayCallbackRoute: AuthEbayCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
